name       : neofetch
version    : 6.0.0
release    : 19
source     :
    - https://github.com/dylanaraps/neofetch/archive/6.0.0.tar.gz : 264a7689561bb498f97f10231959bdd8f7c873671bac2ffb660de9a5863b1c76
license    : MIT
component  : system.utils
summary    : A fast, highly customizable system info script.
description: |
    A fast, highly customizable system info script.
rundeps    :
    - w3m
install    : |
    %make_install
