name       : neofetch
version    : 7.0.0
release    : 21
source     :
    - https://github.com/dylanaraps/neofetch/archive/7.0.0.tar.gz : 8c6bd217cf6d34fc1f3dcbb0e8b1137655bc13fbb21165273dbb2a7bce0d3130
license    : MIT
component  : system.utils
summary    : A fast, highly customizable system info script.
description: |
    A fast, highly customizable system info script.
rundeps    :
    - w3m
setup      : |
    %apply_patches
install    : |
    %make_install
