name       : neofetch
version    : 5.0.0
release    : 17
source     :
    - https://github.com/dylanaraps/neofetch/archive/5.0.0.tar.gz : 2a4f4853bf83b88a037994dbc53a90c8bd5708f5eeb3392f56d4e49c49d995b3
license    : MIT
component  : system.utils
summary    : A fast, highly customizable system info script.
description: |
    A fast, highly customizable system info script.
rundeps    :
    - w3m
install    : |
    %make_install
