name       : neofetch
version    : 4.0.0
release    : 15
source     :
    - https://github.com/dylanaraps/neofetch/archive/4.0.0.tar.gz : b2dae233007ac7d5717df7b1f8f742aebcb84289d5a048398eab3566a8204278
license    : MIT
component  : system.utils
summary    : A fast, highly customizable system info script.
description: |
    A fast, highly customizable system info script.
rundeps    :
    - w3m
setup      : |
    # Fix for pacman game causing error with neofetch
    sed -i 's:pacman:thisaintarch:g' neofetch
install    : |
    %make_install
