name       : neofetch
version    : 3.0.1
release    : 10
source     :
    - https://github.com/dylanaraps/neofetch/archive/3.0.1.tar.gz : 31447da6507c13c44eb2006901c00ed4ca08f0423d9439aaddea64edcaca2c38
license    : MIT
component  : system.utils
summary    : A fast, highly customizable system info script.
description: |
    A fast, highly customizable system info script.
rundeps    :
    - w3m
setup      : |
    %patch -p1 < $pkgfiles/eopkg-vroom-vroom.patch
    # Colors and configuration
    sed -i 's#${XDG_CONFIG_HOME:-${HOME}/.config}#/usr/share#g' config/config
    # Fix for pacman game causing error with neofetch
    sed -i 's:pacman:thisaintarch:g' neofetch
    # Fix w3m_img_path
    sed -i 's|lib/w3m|lib64/w3m|' config/config
install    : |
    %make_install
