name       : neofetch
version    : 3.1.0
release    : 11
source     :
    - https://github.com/dylanaraps/neofetch/archive/3.1.0.tar.gz : db7afe24d859b9c8230c3491640d996701816ddc9cf66f98a5071775e8b4ffe5
license    : MIT
component  : system.utils
summary    : A fast, highly customizable system info script.
description: |
    A fast, highly customizable system info script.
rundeps    :
    - w3m
setup      : |
    # Colors and configuration
    sed -i 's#${XDG_CONFIG_HOME:-${HOME}/.config}#/usr/share#g' config/config
    # Fix for pacman game causing error with neofetch
    sed -i 's:pacman:thisaintarch:g' neofetch
    # Fix w3m_img_path
    sed -i 's|lib/w3m|lib64/w3m|' config/config
install    : |
    %make_install
