name       : neofetch
version    : 3.3.0
release    : 13
source     :
    - https://github.com/dylanaraps/neofetch/archive/3.3.0.tar.gz : 4808e76bd81da3602cb5be7e01dfed8223b1109e2792755dd0d54126014ee696
license    : MIT
component  : system.utils
summary    : A fast, highly customizable system info script.
description: |
    A fast, highly customizable system info script.
rundeps    :
    - w3m
setup      : |
    # Fix for pacman game causing error with neofetch
    sed -i 's:pacman:thisaintarch:g' neofetch
install    : |
    %make_install
